### ISSUE TITLE
Problem about installation

### ISSUE THREAD

**Issue by hkkkpang** [Angtian/VoGE#1]
Hi,

Thanks for your wonderful work!

I have a problem about your code installation. For this line https://github.com/Angtian/VoGE/blob/f0ed68f26e13e93d5c84556309260de455614e94/setup.py#L14, should I change to my cuda directory if I use windows system? Or do I need to change setup.py file?

Best,

**Comment by Angtian** [comment]
Hello,
Have you tried just directly installing VoGE without changing the CUDA_HOME?
It works just keep as it is on my Windows system. Please let me know if you meet any other issues.

**Comment by hkkkpang** [comment]
Hi,

Now I have installed it successfully. Thanks for your help.
